set nocompatible
set hidden
set visualbell
set noerrorbells
set t_vb=
set title
set titleold=
set titlestring=%F
set nobackup
set noswapfile
set ttyfast
set showmatch
set history=1000
set lazyredraw
set clipboard=unnamedplus
set foldmethod=syntax
set foldlevel=99
set shortmess=I
filetype plugin indent on
set number
set ruler
set relativenumber

" wrap long lines
set wrap

" wrap lines at space, tab, or punctuation, and avoid breaking words
set linebreak

" visual ruler for line limits
set colorcolumn=80,100,120

set wildmenu
set wildmode=list:longest,full
set wildignore+=*.exe,*.gif,*.jpeg,*.jpg,*.o,*.pdf,*.png,*.pyc
set mouse=a
set cmdheight=1
set showcmd
set cursorline
set laststatus=2
set statusline=%<%f%y%m%r%=[%{&fileformat}]\ %v\ %l\:%L
syntax enable
set t_Co=256
set backspace=indent,eol,start
set confirm
set encoding=utf-8
set termencoding=utf-8
set fileencoding=utf-8
set autoindent
set smarttab

" show specific characters as per specified
set listchars=eol:¬,tab:▸·,space:·

" show unprintable characters
" set list

set ignorecase
set incsearch
set hlsearch
set smartcase

" make horizontal split appear below the current window
set splitbelow

" move .viminfo into ~/.vim/
set viminfo+=n~/.vim/viminfo

" enable 24b RGB colors in terminal
set termguicolors

" Alabaster color theme
colorscheme alabaster
highlight ColorColumn ctermfg=NONE ctermbg=255 guifg=NONE guibg=#f0f0f0

" Dracula color theme
" packadd! dracula
" let g:dracula_italic=0
" color dracula
" colorscheme dracula
" highlight ColorColumn ctermbg=7 guibg=#e8e8e8
" highlight ColorColumn ctermbg=236 guibg=#343746

" netrw file explorer
let g:netrw_banner=0
let g:netrw_liststyle=3
autocmd FileType netrw setl bufhidden=delete

" GVim settings
if has ("gui_running")
  set guioptions-=T
  set guioptions+=k
  set guioptions-=r
  set guioptions-=L
  set guioptions-=m

  " text font
  set guifont=Fira\ Code\ Retina\ 10

  " default window size
  set lines=35 columns=150
endif
